# This is the main ansible script to deploy the challenge.

# Example on how to run stuff on all hosts of the track
- name: "Setup web server"
  hosts: all,!build
  vars_files:
    - ../track.yaml
  tasks:
    # This is a helper task that loads the tracks' `track.yaml` file and loads the flags as
    # ansible facts (like variables) to use in subsequent steps. The key is the `discourse` tag
    # of the flag.
    - name: "Load flags"
      loop: "{{ flags }}"
      vars:
        key: "{{ (item.tags).discourse }}"
        value: "{{ item.flag }}"
      ansible.builtin.set_fact:
        track_flags: "{{ track_flags | default({}) | combine({key: value}) }}"

    - name: Initial System Upgrade
      ansible.builtin.apt:
        update_cache: true
        install_recommends: false
        upgrade: full

    - name: Install apt dependencies
      ansible.builtin.apt:
        name:
          - curl
          - grep
          - sed
          - zstd
          - git
        state: present

    - name: Check if ollama is installed
      ansible.builtin.stat:
        path: /usr/local/bin/ollama
      register: ollama_exists

    - name: Install Ollama
      ansible.builtin.shell: |
        curl -fsSL https://ollama.ai/install.sh | sh
      when: not ollama_exists.stat.exists

    - name: Unarchive the content of the build
      ansible.builtin.unarchive:
        src: /tmp/nsec/monsatan-chatbot.tar
        dest: /opt/
        owner: root
        group: root
        mode: "0755"

    - name: Create Ollama systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/ollama.service
        owner: root
        group: root
        mode: "0644"
        content: |
          [Unit]
          Description=Ollama Service
          After=network-online.target

          [Service]
          ExecStart=/usr/local/bin/ollama serve
          User=ollama
          Group=ollama
          Restart=always
          RestartSec=3
          Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          Environment="OLLAMA_NUM_PARALLEL=1"
          Environment="OLLAMA_MAX_LOADED_MODELS=1"
          Environment="OLLAMA_HOST=[::1]:11434"
          {% if nsec_production | default(False) | bool %}
          Environment="HTTP_PROXY=http://proxy.ctf-int.internal.nsec.io:3128"
          Environment="HTTPS_PROXY=http://proxy.ctf-int.internal.nsec.io:3128"
          {% endif %}

          [Install]
          WantedBy=default.target

    - name: Create systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/monsatan-chatbot.service
        owner: root
        group: root
        mode: "0644"
        content: |
          [Unit]
          Description=monsatan-chatbot systemd service
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory=/opt/monsatan-chatbot
          ExecStart=/opt/monsatan-chatbot/monsatan-chatbot -b [::]:80
          Restart=on-failure
          RestartSec=3s

          [Install]
          WantedBy=default.target

    - name: Start ollama service
      ansible.builtin.service:
        name: ollama.service
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Download qwen2.5:0.5b model
      ansible.builtin.shell: |
        OLLAMA_HOST=[::1]:11434 /usr/local/bin/ollama pull qwen2.5:0.5b
      register: ollama_list

    - name: Start service
      ansible.builtin.service:
        name: monsatan-chatbot.service
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Reboot
      ansible.builtin.reboot:
