# Post triggered when the player finds the bonus CI print_flag flag.
type: post
# This should be the same for all the posts in the whole track and should match the original topic YAML filename.
topic: monsatan-defacing
trigger:
  type: flag
  # Name of the discourse tag in track.yaml related to your flag.
  tag: monsatan_defacing_flag_3
api:
  user: Axolotzl
body: |-
  Nice detour! You've been able to execute your own code inside the CI! Now, where can you go from there?
