# AUTOGENERATED - No need to change this section #
resource "incus_project" "this" {
  remote = var.incus_remote

  name        = local.track.name
  description = "Project for the ${local.track.name} track"

  config = {
    "features.images"       = "false"
    "user.contacts.dev"     = join(", ", local.track.contacts.dev)
    "user.contacts.qa"      = length(local.track.contacts.qa) > 0 ? join(", ", local.track.contacts.qa) : null
    "user.contacts.support" = length(local.track.contacts.support) > 0 ? join(", ", local.track.contacts.support) : null
  }
}

# AUTOGENERATED - No need to change this section #
resource "incus_network" "this" {
  remote  = var.incus_remote
  project = incus_project.this.name

  name        = substr(local.track.name, 0, 15)
  description = "Network for challenges in the ${local.track.name} track"

  config = {
    "ipv4.address" = var.deploy == "production" ? "none" : null
    "ipv6.address" = "9000:d37e:c40b:ccc0::1/64"
    "ipv6.nat"     = var.deploy == "production" ? "false" : "true"
  }
}

# Some settings can be changed here #
resource "incus_profile" "this" {
  remote  = var.incus_remote
  project = incus_project.this.name

  name        = "containers"
  description = "Default profile for containers in the ${local.track.name} track"

  config = {
    # These limits should only be adjusted if you NEED more resources.
    "limits.cpu"       = "2"
    "limits.memory"    = "256MiB"
    "limits.processes" = "2000"
  }

  device {
    name = "root"
    type = "disk"

    properties = {
      "pool" = "default"
      "path" = "/"
      # This limit should only be adjusted if you NEED more resources.
      "size" = "1GiB"
    }
  }
}

# AUTOGENERATED - No need to change this section #
resource "incus_instance" "this" {
  remote  = var.incus_remote
  project = incus_project.this.name

  for_each = {
    for k, v in try(local.track.instances, {}) : k => v
    if !can(v.is_build_container) || v.is_build_container == var.build_container
  }

  name        = each.key
  description = each.value["description"]

  type = each.value["type"]

  image = each.value["image"]
  profiles = [
    for profile in coalesce(try(each.value["profiles"], []), []) :
    profile == incus_profile.this.name ? incus_profile.this.name : profile
  ]

  config = merge(
    coalesce(try(each.value["config"], {}), {}),
    {
      "environment.http_proxy"  = var.deploy == "production" ? "http://proxy.ctf-int.internal.nsec.io:3128" : null
      "environment.https_proxy" = var.deploy == "production" ? "http://proxy.ctf-int.internal.nsec.io:3128" : null
      "environment.no_proxy"    = var.deploy == "production" ? "127.0.0.1,::1,localhost" : null
    }
  )

  dynamic "device" {
    for_each = coalesce(try(each.value["devices"], []), [])
    content {
      name = device.value.name
      type = device.value.type

      properties = device.value["properties"]
    }
  }

  device {
    name = "eth0"
    type = "nic"

    properties = merge({
      "network" = incus_network.this.name
      "name"    = "eth0"
      },
      try(trimspace(each.value["hwaddr"]), "") != "" ? {
        hwaddr = trimspace(each.value["hwaddr"])
      } : {}
    )
  }

  lifecycle {
    ignore_changes = [running]
  }

  dynamic "wait_for" {
    for_each = coalesce(try(each.value["wait_for"], []), [])
    content {
      type = wait_for.value.type
    }
  }
}

# AUTOGENERATED - No need to change this section #
resource "incus_network_zone_record" "this" {
  remote = var.incus_remote

  # This resource is generated for each instances (from the track.yaml file)
  for_each = {
    for k, v in local.track.instances : k => v
    if try(trimspace(v.record), "") != ""
  }

  zone = var.ctf_dns_network_zone

  name        = each.value["record"]
  description = each.value["description"]

  entry {
    type  = "AAAA"
    ttl   = 3600
    value = each.value["ipv6"]
  }
}

# If you need to manually add DNS records, here is an example.
#resource "incus_network_zone_record" "sub" {
#  remote = var.incus_remote
#
#  zone = "ctf"
#
#  name        = "sub.chal5.hackademy"
#  description = local.track.instances["challenge5"]["description"]
#
#  entry {
#    type  = "AAAA"
#    ttl   = 3600
#    value = "${local.track.instances["challenge5"]["ipv6"]}"
#  }
#}