[package]
name = "dartreg"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.3", features = ["multipart"] }
clap = { version = "4.5.35", features = ["derive"] }
flate2 = "1.0"
hex = "0.4"
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls", "charset"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.10"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
subtle = "2.6.1"
tar = "0.4"
tokio = { version = "1.44.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
utoipa = "5.4.0"
utoipa-axum = "0.2.0"
uuid = { version = "1", features = ["v4"] }
