//! Mock data seeding for the initial database population.
//!
//! Inserts [`ORDER_COUNT`] fake orders with sequential timestamps when the
//! `orders` table is first created. The output is deterministic: the same
//! [`RNG_SEED`] always produces the same dataset.

use chrono::{Duration, TimeZone, Utc};
use rand::prelude::IndexedRandom;
use rand::rngs::StdRng;
use rand::{RngExt, SeedableRng};
use sqlx::SqlitePool;

use crate::catalog::CATALOG;
use crate::models::OrderItem;

// ---------------------------------------------------------------------------
// Tuning constants
// ---------------------------------------------------------------------------

/// Total number of mock orders to generate on first boot.
const ORDER_COUNT: usize = 13_591;

/// ID of the invoice generated by Monsatan itself.
const MONSATAN_INVOICE_ID: usize = 10_394;

/// Seed for the RNG. Fixed so every fresh database contains the exact same
/// dataset.
const RNG_SEED: u64 = 0xDEAD_BEEF_CAFE_1337;

/// Earliest timestamp for the first mock order (year, month, day).
const SEED_START: (i32, u32, u32) = (2026, 2, 13);

/// Minimum gap between consecutive orders (seconds).
const MIN_GAP_SECS: i64 = 60; // 1 minute

/// Maximum gap between consecutive orders (seconds).
const MAX_GAP_SECS: i64 = 600; // 10 minutes

/// Maximum number of distinct line items per order.
const MAX_ITEMS_PER_ORDER: usize = 3;

/// Maximum quantity of a single product per line item.
const MAX_ITEM_QTY: u32 = 10;

// ---------------------------------------------------------------------------
// Customer data pools
// ---------------------------------------------------------------------------

const FIRST_NAMES: &[&str] = &[
    "Alice", "Bob", "Charlie", "Diana", "Eve", "Frank", "Grace", "Henry", "Iris", "Jack", "Karen",
    "Liam", "Mia", "Noah", "Olivia", "Paul", "Quinn", "Rachel", "Sam", "Tina",
];

const LAST_NAMES: &[&str] = &[
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Wilson",
    "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Lee",
    "Robinson", "Clark",
];

const EMAIL_DOMAINS: &[&str] = &[
    "agro-corp.com",
    "farmtech.io",
    "globalcrops.net",
    "greenfarms.co",
    "verdachem-partner.com",
    "agriworld.biz",
    "cropmaster.org",
];

const STREET_NAMES: &[&str] = &[
    "Main St",
    "Oak Ave",
    "Maple Dr",
    "Cedar Ln",
    "Pine Rd",
    "Elm St",
    "Willow Way",
    "Farm Rd",
    "Industrial Blvd",
    "Commerce Dr",
];

/// `(city, state_abbr)` pairs used to build shipping addresses.
const CITIES: &[(&str, &str)] = &[
    ("Springfield", "IL"),
    ("Riverside", "CA"),
    ("Greenville", "SC"),
    ("Salem", "OR"),
    ("Madison", "WI"),
    ("Lincoln", "NE"),
    ("Farmington", "MN"),
    ("Clayton", "MO"),
    ("Burlington", "VT"),
    ("Georgetown", "TX"),
];

// ---------------------------------------------------------------------------
// Seeding logic
// ---------------------------------------------------------------------------

/// Insert [`ORDER_COUNT`] mock orders into the database if the table is empty.
///
/// All inserts are wrapped in a single transaction for performance. This
/// function is idempotent: if the `orders` table already contains rows it
/// returns immediately without touching anything.
pub async fn seed_orders_if_empty(pool: &SqlitePool) -> Result<(), sqlx::Error> {
    let (count,): (i64,) = sqlx::query_as("SELECT COUNT(*) FROM orders")
        .fetch_one(pool)
        .await?;

    if count > 0 {
        tracing::info!(
            "Orders table already populated ({} rows), skipping seed.",
            count
        );
        return Ok(());
    }

    tracing::info!("Seeding {} mock orders …", ORDER_COUNT);

    // Seeded for deterministic output across runs.
    let mut rng = StdRng::seed_from_u64(RNG_SEED);

    let (year, month, day) = SEED_START;
    let mut current_ts = Utc
        .with_ymd_and_hms(year, month, day, 0, 0, 0)
        .single()
        .expect("SEED_START is a valid date");

    let mut tx = pool.begin().await?;

    for _ in 0..ORDER_COUNT {
        // Advance the timestamp by a random gap so IDs and created_at stay in sync.
        current_ts += Duration::seconds(rng.random_range(MIN_GAP_SECS..=MAX_GAP_SECS));
        let created_at = current_ts.to_rfc3339();

        // Build a random customer.
        let first = FIRST_NAMES.choose(&mut rng).unwrap();
        let last = LAST_NAMES.choose(&mut rng).unwrap();
        let customer_name = format!("{} {}", first, last);

        let domain = EMAIL_DOMAINS.choose(&mut rng).unwrap();
        let customer_email = format!(
            "{}.{}@{}",
            first.to_lowercase(),
            last.to_lowercase(),
            domain
        );

        let street_num: u32 = rng.random_range(1..=9999);
        let street = STREET_NAMES.choose(&mut rng).unwrap();
        let (city, state) = CITIES.choose(&mut rng).unwrap();
        let zip: u32 = rng.random_range(10000..=99999);
        let shipping_address = format!("{} {}, {}, {} {}", street_num, street, city, state, zip);

        // Pick 1–MAX_ITEMS_PER_ORDER distinct products.
        let n_items = rng.random_range(1..=MAX_ITEMS_PER_ORDER);
        let mut items: Vec<OrderItem> = Vec::with_capacity(n_items);
        let mut used_indices: Vec<usize> = Vec::with_capacity(n_items);

        for _ in 0..n_items {
            // Walk forward from a random position to avoid duplicate products.
            let mut idx = rng.random_range(0..CATALOG.len());
            let mut attempts = 0;
            while used_indices.contains(&idx) && attempts < CATALOG.len() {
                idx = (idx + 1) % CATALOG.len();
                attempts += 1;
            }
            used_indices.push(idx);

            let qty: u32 = rng.random_range(1..=MAX_ITEM_QTY);
            items.push(OrderItem {
                product_id: CATALOG[idx].id.to_owned(),
                quantity: qty,
            });
        }

        // Compute the order total in cents from the catalog prices.
        let total_cents: i64 = items
            .iter()
            .map(|item| {
                let price = CATALOG
                    .iter()
                    .find(|p| p.id == item.product_id)
                    .map(|p| p.price_cents)
                    .unwrap_or(0);
                price as i64 * item.quantity as i64
            })
            .sum();

        let items_json = serde_json::to_string(&items).expect("OrderItem always serializes");

        sqlx::query(
            r#"
            INSERT INTO orders
                (customer_name, customer_email, shipping_address, items, total_cents, created_at)
            VALUES (?, ?, ?, ?, ?, ?)
            "#,
        )
        .bind(&customer_name)
        .bind(&customer_email)
        .bind(&shipping_address)
        .bind(&items_json)
        .bind(total_cents)
        .bind(&created_at)
        .execute(&mut *tx)
        .await?;
    }

    // Insert the Monsatan invoice.
    sqlx::query(
        r#"
        UPDATE orders
        SET customer_name = ?, customer_email = ?, shipping_address = ?
        WHERE id = ?
        "#,
    )
    .bind("Monsatan Ltd.")
    .bind("procurement@monsatan.ctf")
    .bind(
        "
        Lot 666, Greenwash Industrial Corridor
        1 Eternal Growth Parkway
        Neo-St. Louis, Missouri Reclamation Zone
        UCSA 63166-MON
        FLAG-{e2749e7242053c78fe45594f6882f18c}
        ",
    )
    .bind(MONSATAN_INVOICE_ID.to_string())
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    tracing::info!("Seed complete: {} orders inserted.", ORDER_COUNT);
    Ok(())
}
