# This is an example post after submitting a flag.
type: post
# This should be the same for all the posts in the whole track and should match the original topic YAML filename.
topic: monsatan-mailserver
trigger:
  type: flag
  # Name of the discourse tag in track.yaml related to your flag.
  tag: monsatan_mailserver_flag_1
api:
  user: Axolotzl
body: |-
  Seems like you got a foothold. Good job on leaking the database credentials.

  However, those aren't good enough if you can't get into the actual mailboxes. Keep digging.
