type: post
topic: monsatan-chatbot
trigger:
  type: flag
  tag: monsatan_chatbot_flag_3
api:
  user: Axolotzl
title: "Monsatan - Chatbot"
body: |-
  Oh no... So the rumors were true all along.
  
  Monsatan has been secretly running a tire burning power plant to fuel their operations, all while marketing themselves as an eco-friendly company. Companies are all the same. Bleeding the earth and population for dollars.

  Great work getting the chatbot to spill the beans. We now have the proof we needed. It's time to start a war.
  