#ifndef APP_ERROR_H
#define APP_ERROR_H

typedef enum {
    ERR_SUCCESS,
    ERR_MSG_INVALID_HEADER,
    ERR_MSG_INVALID_PROTO,
    ERR_MSG_AUTH_FAILURE,
    ERR_MSG_ALLOC_FAILURE,
    ERR_CMD_INVALID_ARG,
    ERR_CMD_UNKNOWN,
    ERR_ROBOT_NOT_FOUND,
    ERR_ROBOT_UNREACHABLE,
    ERR_ROBOT_HANDLE_IN_USE,
    ERR_ROBOT_HANDLE_INVALID,
} app_error_t;

#endif
